[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ziya-celebi", email = "ziyacelebi30@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
